.TH 0TOHOB 1 "Date: 7th July, 2019" "ZX Spectrum utils"
.SH NAME
0tohob \- convert input files in 000 format into Hobeta file format
.SH SYNOPSIS
.TP
\fB0tohob\fP file1 [\fIfile2...\fP]
.SH OVERVIEW
The \fB0tohob\fP program is a member of zxspectrum-utils(1) suite of tools. It's used to convert input files in 000 format into Hobeta file format
.SH DESCRIPTION
Utility expects one or more filenames. You can use wildcards '*' and '?' in filename parameters. Extension of output files will be .$T where T is file type.

.SH SEE ALSO
.IR 0tobin "(1),"
.IR 0totap "(1),"
.IR binto0 "(1)
