.TH BIN2MBD 1 "Date: 7th July, 2019" "ZX Spectrum utils"
.SH NAME
bin2mbd \- convert binary file into .mbd file
.SH SYNOPSIS
.TP
\fBbin2mbd\fP [\fIoptions\fP] \fI[input_file]\fP
.SH OVERVIEW
The \fBbin2mbd\fP program is a member of zxspectrum-utils(1) suite of tools. Use it to convert raw file into CODE block in a .mbd file.
.SH DESCRIPTION
You can specify new target file or use existing one (it can add to existing images aswell) or target file can be created from input file name if you don't specify it. Program can be used for creating empty disc images when you specify just output file name.

All options are optional. If some option is requied and not set, it's used default value. You must set input file name, output file name or both of them.

.SH OPTIONS
.B \-nt
.I <arg>
.RS
Number of tracks of new disc image, default
.I 82
.RE
.PP
.B \-ns
.I <arg>
.RS
Number of sectors of new disc image, default
.I 11
.RE
.PP
.B \-nsur
.I <arg>
.RS
Number of surfaces of new disc, default
.I 2
.RE
.PP
.B \-d
.I <arg>
.B \--dir
.I <arg>
.RS
Number of directory where the program put the file, default
.I 0
.RE
.PP
.B \-a
.I <arg>
.RS
Starting address of binary file
.RE
.PP
.B \-o
.I <file>
.RS
Set output file
.RE
.PP
.B  \-h
.B \--help
.RS
Show help text
.RE
.PP
.B \-v
.B \--version
.RS
Show version of program
.RE
.PP

.SH SEE ALSO
.IR mb2tap "(1),"
.IR mbdcheck "(1),"

