.TH DIRHOB 1 "Date: 12th July, 2019" "ZX Spectrum utils"
.SH NAME
dirhob \- print header information of input file in Hobeta format
.SH SYNOPSIS
.TP
\fBdirhob\fP \fIfile1\fP [\fIfile2 ...\fP]
.SH OVERVIEW
The \fBdirhob\fP program is a member of zxspectrum-utils(1) suite of tools. Utility print header information of input file(s).
.SH DESCRIPTION
Utility expect one or more file names and print header informations: file name, header name, extension, lenght, sectors lenght, starting address. You can use wildcards '*' and '?' in filename parameters.

.SH SEE ALSO
.IR 0tohob "(1),"
.IR hobto0 "(1),"
.IR dir0 "(1),"
.IR dirtap "(1)
