.TH HOBETA2TRD 1 "Date: 12th July, 2019" "ZX Spectrum utils"
.SH NAME
hobeta2trd \- copy HOBETA files to TRDOS disk image
.SH SYNOPSIS
.TP
\fBhobeta2trd\fP [\fIoptions\fP] source target
.SH OVERVIEW
The \fBhobeta2trd\fP program is a member of zxspectrum-utils(1) suite of tools. Use it to copy hobeta files to TRDOS disk image.
.SH DESCRIPTION
You must specify source hobeta file and target trdos disk image.

.SH OPTIONS
.B \-V
.br
.B \-\-verbose
.RS
Increase verbosity level
.RE
.PP
.B \-f
.br
.B \-\-force
.RS
Force copy. Do not check trdos identification in target file.
.RE
.PP
.B \-h
.br
.B \-\-help
.RS
Print help text
.RE
.PP
.B \-v
.br
.B \-\-version
.RS
Print version
.RE
.PP

.SH SEE ALSO
.IR 0tohob "(1),"
.IR dirboh "(1),"
.IR hobto0 "(1),"
.IR lstrd "(1)"

