.TH DIR0 1 "Date: 12th July, 2019" "ZX Spectrum utils"
.SH NAME
dir0 \- print header information of input file in 000 format
.SH SYNOPSIS
.TP
\fBdir0\fP [\fI-p\fP] \fIfile1\fP [\fIfile2 ...\fP]
.SH OVERVIEW
The \fBdir0\fP program is a member of zxspectrum-utils(1) suite of tools. Utility print header information of input file(s).
.SH DESCRIPTION
Utility expect one or more file names and print header informations: file name, file type, header name, lenght, start of code, start of basic, lenght and flag. If you specify \fI-p\fP parameter, utility will check and print parity. You can use wildcards '*' and '?' in filename parameters.

.SH OPTIONS
.B -p
.RS
Additional parity tester
.RE
.PP

.SH SEE ALSO
.IR 0tohob "(1),"
.IR 0totap "(1),"
.IR 0tobin "(1)
