.TH HOBTO0 1 "Date: 12th July, 2019" "ZX Spectrum utils"
.SH NAME
hobto0 \- convert input files in Hobeta format into 000 file format
.SH SYNOPSIS
.TP
\fBhobto0\fP file1 [\fIfile2...\fP]
.SH OVERVIEW
The \fBhobto0\fP program is a member of zxspectrum-utils(1) suite of tools. It's used to convert input files in Hobeta format into 000 file format
.SH DESCRIPTION
Utility expects one or more filenames. You can use wildcards '*' and '?' in filename parameters. Extension of output file will be three-digit number, starting at 000 and increasing if file with this name already exist.

.SH SEE ALSO
.IR 0tobin "(1),"
.IR 0totap "(1),"
.IR binto0 "(1)
